{
  "patch_version": "1.0.0",
  "manager_versions": ["4.4.0","4.4"],
  "community": true,
  "premium": true,
  "patches": [
    {
      "patch_file": "fix_snapshot_encrypt_secrets.patch",
      "md5sum": "47bd0a37871afab317dd45186cb79997",
      "destinations": ["/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_system_workflows/snapshots/postgres.py"]
    }
  ],
  "affected_services": [
    "cloudify-mgmtworker"
  ],
  "md5sums_before": {
    "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_system_workflows/snapshots/postgres.py": ["d8ded7ad223095fe8f061f58067e20d2"]
  },
  "md5sums_after": {
    "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify_system_workflows/snapshots/postgres.py": ["d14b12d8561b447e19fffa31c4971981"]
  }
}

